In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
db=pd.read_csv("employees.csv")

db

,First Name,Last Name,Email,Phone,Gender,Age,Job Title,Years Of Experience,Salary,Department
0,Jose,Lopez,joselopez0944@slingacademy.com,+1-971-533-4552x1542,male,25,Project Manager,1,8500,Product
1,Diane,Carter,dianecarter1228@slingacademy.com,881.633.0107,female,26,Machine Learning Engineer,2,7000,Product
2,Shawn,Foster,shawnfoster2695@slingacademy.com,001-966-861-0065x493,male,37,Project Manager,14,17000,Product
3,Brenda,Fisher,brendafisher3185@slingacademy.com,001-574-564-4648,female,31,Web Developer,8,10000,Product
4,Sean,Hunter,seanhunter4753@slingacademy.com,5838355842,male,35,Project Manager,11,14500,Product
...,...,...,...,...,...,...,...,...,...,...
315,Michelle,Hooper,michellehooper315396@slingacademy.com,401.041.6802,female,29,Web Developer,4,9000,Product
316,Steven,Lewis,stevenlewis316274@slingacademy.com,+1-584-489-5663x896,male,34,Web Developer,11,11500,Product
317,Kevin,Rodriguez,kevinrodriguez317974@slingacademy.com,001-511-226-4416x83410,male,29,Web Developer,5,8500,Product
318,Alexandra,Bell,alexandrabell318109@slingacademy.com,+1-426-702-6363x565,female,39,Web Developer,14,13000,Product
319,Courtney,Mcdaniel,courtneymcdaniel319568@slingacademy.com,(871)098-2647x80448,female,28,Web Developer,3,8500,Product

In [4]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   First Name           320 non-null    object
 1   Last Name            320 non-null    object
 2   Email                320 non-null    object
 3   Phone                320 non-null    object
 4   Gender               320 non-null    object
 5   Age                  320 non-null    int64
 6   Job Title            320 non-null    object
 7   Years Of Experience  320 non-null    int64
 8   Salary               320 non-null    int64
 9   Department           320 non-null    object
dtypes: int64(3), object(7)
memory usage: 25.1+ KB

In [5]:
db.drop(columns=["First Name","Last Name","Email",	"Phone",	"Gender", "Age", "Department"])

                     Job Title  Years Of Experience  Salary
0              Project Manager                    1    8500
1    Machine Learning Engineer                    2    7000
2              Project Manager                   14   17000
3                Web Developer                    8   10000
4              Project Manager                   11   14500
..                         ...                  ...     ...
315              Web Developer                    4    9000
316              Web Developer                   11   11500
317              Web Developer                    5    8500
318              Web Developer                   14   13000
319              Web Developer                    3    8500

[320 rows x 3 columns]

In [6]:
X=db[["Job Title",	"Years Of Experience"]]

In [7]:
X

                     Job Title  Years Of Experience
0              Project Manager                    1
1    Machine Learning Engineer                    2
2              Project Manager                   14
3                Web Developer                    8
4              Project Manager                   11
..                         ...                  ...
315              Web Developer                    4
316              Web Developer                   11
317              Web Developer                    5
318              Web Developer                   14
319              Web Developer                    3

[320 rows x 2 columns]

In [8]:
y=db["Salary"]

In [9]:
y

0       8500
1       7000
2      17000
3      10000
4      14500
       ...
315     9000
316    11500
317     8500
318    13000
319     8500
Name: Salary, Length: 320, dtype: int64

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

In [11]:
cf = ["Job Title"]
nf = ["Years Of Experience"]

In [15]:
preprocessor = ColumnTransformer([
    ("job", OneHotEncoder(), cf)], remainder="passthrough")

In [21]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('job', OneHotEncoder(), ['Job Title'])])

In [26]:
from sklearn.pipeline import Pipeline
pipeline = Pipeline([("preprocessing", preprocessor), ("model", LinearRegression())])

In [27]:
print(pipeline)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('job', OneHotEncoder(),
                                                  ['Job Title'])])),
                ('model', LinearRegression())])

In [24]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2)

In [28]:
pipeline.fit(train_X, train_y)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('job', OneHotEncoder(),
                                                  ['Job Title'])])),
                ('model', LinearRegression())])

In [30]:
y_pred = pipeline.predict(test_X)
y_pred

array([13095.8832881 , 10345.61758912, 10043.25754589,  8481.70118762,
        8948.47221861,  7393.19306755, 10864.04397281, 13095.8832881 ,
       14709.09499906, 12577.45690441,  8430.04583492,  6874.76668386,
        6407.99565287,  8241.09776322,  6926.42203656,  7393.19306755,
       12059.03052072, 11022.17775335,  9518.55395499,  6407.99565287,
        9308.76482175, 13425.36160008, 15745.94776644, 11540.60413704,
        9985.32498598, 10314.80329796,  6874.76668386,  6926.42203656,
       10561.68392957,  8430.04583492, 11598.53669695,  8528.92943669,
        9466.89860229, 14231.61965724,  7393.19306755,  7911.61945123,
        8430.04583492,  7198.65488973,  8948.47221861, 11022.17775335,
       10555.40672236,  6356.34030017, 13614.30967178,  7911.61945123,
        7722.67137953,  7717.08127341,  7492.07666932,  7393.19306755,
        9466.89860229,  7393.19306755,  9047.35582038, 11346.06595922,
        6407.99565287, 10043.25754589,  9985.32498598, 13665.96502448,
        7444.84842025,  7444.84842025,  9308.76482175, 10036.98033868,
       14709.09499906, 13013.81978776,  8235.5076571 ,  8948.47221861])

In [31]:

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
r2 = r2_score(test_y, y_pred)
mae = mean_absolute_error(test_y, y_pred)
mse = mean_squared_error(test_y, y_pred)

In [32]:
print(r2)
print(mae)
print(mse)

0.8659463271643537
763.6143218513615
863878.7194217558

In [34]:


result = pd.DataFrame({
    "Actual": test_y,
    "Predicted": y_pred
})

print(result.head())

     Actual     Predicted
203   12000  13095.883288
72     9500  10345.617589
195    9000  10043.257546
183    9500   8481.701188
62     9000   8948.472219

In [35]:
import joblib
joblib.dump(pipeline, "model.pkl")

['model.pkl']

In [37]:
import pickle
pickle_out=open("pipeline.pkl","wb")
pickle.dump(pipeline, pickle_out)
pickle_out.close()